# Tareas {-}

```{r options, echo = FALSE, message=FALSE, error=TRUE}
knitr::opts_chunk$set(
    comment = "#>",
    collapse = TRUE, error=TRUE
)
comma <- function(x) format(x, digits = 2, big.mark = ",")
options(digits = 3)

library(tidyverse)
theme_set(theme_minimal())
```

* Las tareas se envían por correo a teresa.ortiz.mancera@gmail.com con título: 
EstComp-TareaXX (donde XX corresponde al número de tarea, 01..). 

* Las tareas deben incluir código y resultados (si conocen [Rmarkdown](https://rmarkdown.rstudio.com) 
es muy conveniente para este propósito).

### 1. Instalación y visualización

1. Instala los siguientes paquetes (o colecciones):
    + tidyverse de CRAN (`install.packages(tidyverse)`)
    + devtools de CRAN (`install.packages(devtools)`)
    + gapminder de CRAN (`install.packages(gapminder)`)
    + estcomp de GitHUB (debes haber instalado devtools y correr
    `devtools::install_github("tereom/estcomp")`))
    + mxmaps **opcional** de [GitHub](https://github.com/diegovalle/mxmaps#installation)


2. Visualización

* Elige un base de datos, rcuerda que en la ayuda puedes encontrar más 
información (`?gapminder`): 
    + gapminder (paquete `gapminder` en CRAN).
    + election_2012 ó election_sub_2012 (paquete `estcomp`).
    + df_edu (paquete `estcomp`).
    + enlacep_2013 o un subconjuto de este (paquete `estcomp`).

* Escribe algunas preguntas que consideres interesantes de los datos.

* Realiza $3$ gráficas buscando explorar las pregunutas de arriba y explica las
relaciones que encuentres. Debes usar lo que revisamos en estas notas y al menos
una de las gráficas debe ser de paneles (usando `facet_wrap()` o `facet_grid`).


